### ISSUE TITLE
gereksinimler ve kısıtlar

### ISSUE THREAD

**Issue by poyrazenes** [poyrazenes/BBM487-20142-5#10]
sistemin analiz ederek gereksinimlerini ve kısıtlamaları varsayımlarınızla birlikte açıklayınız.

**Comment by sezenkilickaya** [comment]
Sistem analizi sonucu gereksinim ve kısıtlamalar belirlendi.
Gereksinim olarak kullanılacak veri set özellikleri, verilerin birbirleriyle ilişkileri ve kullanıcıların sistemde yapmaları istenen işlemler çıkarıldı. 
Öğrenci, akademik personel ve öğrenci işleri personeli için 3 farklı arayüz gereksinimi , 
ders ekle/sil işlemlerinde herkesin rahat ulaşabileceği ve kullanabileceği bir tasarım , 
network problemi yaşanmaması için yeterli kapasiteye sahip bir network ağı üzerinden işlem yapabilme ,
 kullanıcıların sisteme gireceği ortamlar göz önünde bulundurularak tüm ortamlara uygun bir yazılım geliştirme , 
sistemdeki kayıtlı kullanıcı sayısının artacağı göz önünde bulundurularak fazla kısıtlı olmayan bir veritabanı özellikleri olmalıdır.

Kısıtlama olarak, projede kullanacağımız veriler veritabanı üzerinden olmayacak. Web tabanlı bir uygulama yapılacaktır.

Eklenebilecek yeni özellikler ve veriler olduğunu varsayarak projeye temel özellikler öne alınıp başlanmasına karar verildi.
