### ISSUE TITLE
use case diagrams

### ISSUE THREAD

**Issue by poyrazenes** [poyrazenes/BBM487-20142-5#13]
Sistem temel fonksiyonları UML use case diyagramı çizerek gösteriniz. Her bir use case’i bir kaç cümle ile anlatınız.

**Comment by kemalAltinok** [comment]
Sistemi kullanacak olan varlıklar ve sistemde bulunabilecek ögeler tespit edildi. (Öğrenci, Akademisyen, Personel, Seçilen Dersler, Bölümler, Öğrenci Notları, Dönem... gibi)
Ardından bu varlıklara bağlı fonksiyonlar belirlenip, UML Diagramıyla birlikte ifade edildi.
Temelde bu fonksiyonlar, öğrenci, akademisyen ve personellerin kullanım ihtiyaçlarına yönelik, spesifik olarak sınıflandırıldı.
