### ISSUE TITLE
domain analizi

### ISSUE THREAD

**Issue by poyrazenes** [poyrazenes/BBM487-20142-5#14]
Domain analizi yaparak, bu alanla ilgili class’ları ve ilişkileri UML Class Diyagram kullanarak gösteriniz. Aynı diyagram üzerinde veri gereksinimlerini classların attribute’ları olarak belirtiniz.

**Comment by sezenkilickaya** [comment]
Domain analizi yapılarak kullanılacak classlar belirlendi ve diagram üzerinde gösterildi.
Veri gereksinimleri , class attributeları olarak eklendi.
![screen shot 2015-03-11 at 17 21 38](https://cloud.githubusercontent.com/assets/11196777/6599607/7e1185a6-c813-11e4-81a3-41637906d6e1.png)
![screen shot 2015-03-11 at 17 22 23](https://cloud.githubusercontent.com/assets/11196777/6599623/8baa2240-c813-11e4-98ca-82c922e73be0.png)
