### ISSUE TITLE
tasarım belgesi hazırlama

### ISSUE THREAD

**Issue by poyrazenes** [poyrazenes/BBM487-20142-5#17]
ikinci teslim için hazırlanan gereksinim belgesine uygun bir tasarım dökümanı oluşturunuz.

**Comment by kemalAltinok** [comment]
İkinci teslim için hazırlanan tasarım belgesinde gerekli UML diyagramları devam niteliğinde oluşturulup, güncel arayüzler ve ikonlar dökümana ilave edildi.
