### ISSUE TITLE
arayüzlerin tasarlanması

### ISSUE THREAD

**Issue by poyrazenes** [poyrazenes/BBM487-20142-5#9]
oluşturulacak sistemin kullanıcı arayüzlerini tasarlayınız

**Comment by kemalAltinok** [comment]
Oluşturulacak sistemin kullanıcı arayüzleri özellikle öğrenci, akademisyen ve personelin kolay bir şekilde işlemlerini yapabilmesine olanak tanıyacak şekilde tasarlandı. Birbiriyle bağlantısı olan arayüzlerin ve ögelerinin etkileşim biçimi şemalarla ifade edildi.
